@startmindmap jvm
* JVM
** JVM 内存布局
*** 虚拟机栈
*** 本地方法栈
*** 程序计数器
*** 堆
****_ 对象的创建
****_ 对象的内存布局
****_ 对象的访问定位
*** 方法区
**** 运行时常量池
*** 直接内存
** 垃圾收集器
*** 判断对象是否存活的算法
****_ 引用计数算法
****_ 可达性分析算法
*** 垃圾收集算法
**** 分代收集理论
*****_ 标记复制算法
*****_ 标记清除算法
*****_ 标记整理算法
*** 经典垃圾收集器
****_ Serial 收集器
****_ Serial old 收集器
****_ ParNew 收集器
****_ CMS 收集器
****_ Parallel Scavenge 收集器
****_ Parallel Old 收集器
*** Full GC触发条件
**** 老年代已满
*****_ 大对象直接进入老年代
*****_ 长期存活分代年龄达标进入老年代
*****_ 空间分配担保
**** 元空间已满
*****_ OutOfMemoryError: Metaspace
@endmindmap

@startmindmap 性能监控和故障处理工具
* 性能监控和故障处理工具
** jps
** jstat
@endmindmap




